// <auto-generated />
namespace PurwadhikaWebApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedfirstnamelastnameinidentitymodelsanduserviewmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedfirstnamelastnameinidentitymodelsanduserviewmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201610090712271_added firstname lastname in identitymodels and userviewmodel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
