// <auto-generated />
namespace PurwadhikaWebApplication.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class editJobMaster_RenameProperty_and_AddJobStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(editJobMaster_RenameProperty_and_AddJobStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201701210632494_editJobMaster_RenameProperty_and_AddJobStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
